# syntax=docker/dockerfile:1

##Build
FROM golang:1.19.2-alpine AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN go build -o /docker-auth-server

##Deploy
FROM gcr.io/distroless/base-debian11

WORKDIR /

COPY --from=build /docker-auth-server /docker-auth-server

EXPOSE 8089

USER nonroot:nonroot

ENTRYPOINT ["/docker-auth-server"]
