apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-backend
  template:
    metadata:
      labels:
        app: auth-backend
    spec:
      containers:
        - name: auth-backend
          image: auth-backend-image
          ports:
            - containerPort: 8089

---
apiVersion: v1
kind: Service
metadata:
  name: auth-backend-service
spec:
  selector:
    app: auth-backend
  ports:
    - port: 8089
      targetPort: 8089
