apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-backend
  template:
    metadata:
      labels:
        app: auth-backend
    spec:
      containers:
        - name: auth-backend
          image: auth-backend-image
          env:
            - name: MONGO_DB_USERNAME
              value: "mongoUser"
            - name: MONGO_DB_PASSWORD
              value: "mongoPassword"
          ports:
            - containerPort: 8089

---
apiVersion: v1
kind: Service
metadata:
  name: auth-backend-service
spec:
  selector:
    app: auth-backend
  ports:
    - port: 8089
      targetPort: 8089

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend
spec:
  ingressClassName: nginx
  rules:
    - host: "authserver.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-backend-service
                port:
                  number: 8089