apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-frontend
  template:
    metadata:
      labels:
        app: auth-frontend
    spec:
      containers:
        - name: auth-frontend
          image: auth-frontend-image
          env:
            - name: AUTH_SERVER
              value: "auth-backend-service"
          ports:
            - containerPort: 8090

---

apiVersion: v1
kind: Service
metadata:
  name: auth-frontend-service
spec:
  selector:
    app: auth-frontend
  ports:
    - port: 8090
      targetPort: 8090

