apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-frontend
  template:
    metadata:
      labels:
        app: auth-frontend
    spec:
      containers:
        - name: auth-frontend
          image: auth-frontend-image
          env:
            - name: AUTH_SERVER
              value: "auth-backend-service"
          ports:
            - containerPort: 8090


---

apiVersion: v1
kind: Service
metadata:
  name: stock-analyzer-service
spec:
  type: NodePort
  selector:
    app: stock-analyzer
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 30007

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-stock-analyzer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: stockanalyzer.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stock-analyzer-service
                port:
                  number: 8088